name: CSB2025
channels:
  - colomoto
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - seaborn
  - statsmodels
  - networkx
  - jupyterlab
  - ipykernel
  - notebook
  - ipywidgets
  - ipylab
  - graphviz
  - pygraphviz
  - pydot
  - colomoto_jupyter
  - cmaboss
  - maboss
  - ginsim
  - ginsim-python
  - boolsim
  - boolsim-python
  - bns
  - bns-python
  - boolean.py
  - espresso-logic-minimizer
  - clingo
  - nusmv
  - pymaboss
  - pip
  - pip:
      - ipylab==1.1.0